# Generated by Django 4.2.7 on 2023-12-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilecategory',
            options={'ordering': ('order',), 'verbose_name_plural': 'Mobile Category'},
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, upload_to='mobile/')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobiles', to='store.mobilecategory')),
            ],
            options={
                'verbose_name_plural': 'Mobiles',
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='mobile',
            constraint=models.UniqueConstraint(fields=('order', 'category'), name='unique_order_category'),
        ),
        migrations.AlterUniqueTogether(
            name='mobile',
            unique_together={('id', 'slug')},
        ),
    ]
