# Generated by Django 4.2.7 on 2024-01-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('small_text', models.TextField()),
                ('photo', models.ImageField(upload_to='bannerpromo/')),
                ('button_text', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
