# Generated by Django 4.2.7 on 2024-01-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bannerpromo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('order', models.PositiveIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'WatchCategory',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AppleWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(help_text='Enter the color of the Apple Watch (e.g., Black, White, Blue, etc.)', max_length=50)),
                ('size', models.CharField(help_text='Enter the size of the Apple Watch (e.g., 42mm, 38mm, etc.)', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, upload_to='applewatch/')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applewatches', to='store.watchcategory')),
            ],
            options={
                'verbose_name_plural': 'Watches',
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='applewatch',
            constraint=models.UniqueConstraint(fields=('order', 'category'), name='unique_order_applewatch'),
        ),
        migrations.AlterUniqueTogether(
            name='applewatch',
            unique_together={('id', 'slug')},
        ),
    ]
