# Generated by Django 4.2.7 on 2024-01-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_watchcategory_applewatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applewatch',
            name='photo',
            field=models.ImageField(blank=True, help_text='Enter the size (1200x1200)', upload_to='applewatch/'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Enter the size (1200x1200)', upload_to='mobile/'),
        ),
    ]
