# Generated by Django 4.2.7 on 2024-01-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_app', '0002_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased',
            name='products',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
